name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spec_validator:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      # TODO(mimir-d): temporary disable until json schema is fully updated for v2
      # - name: unittests
      #   run: ./ci_scripts/run_validator_tests.sh
      # - name: validate samples
      #   run: ./ci_scripts/validate_spec_samples.sh
